import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppShell from "./components/AppShell";

import { Inter, Playfair_Display } from "next/font/google";

export const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

export const playfair = Playfair_Display({
	variable: "--font-playfair",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html
			lang="en"
			className={`${playfair.variable} ${inter.variable} h-full antialiased`}
		>
			<body className="min-h-dvh flex flex-col">
				<AppShell>{children}</AppShell>
			</body>
		</html>
	);
}
